### ISSUE TITLE
Sondages : graphiques et ajout d'option/question

### ISSUE THREAD

**Issue by Titijaff** [consortium-horizon/apps#18]
Les sondages semblent avoir perdu leurs graphiques (barres jaunes orange), lors de la création, l'ajout d'option ou question renvoi vers une page introuvable... de même que l'affichage du sondage dans le fil du sujet.

**Comment by pkonecki** [comment]
Fixed en 469db6b0fc239e0d710a59ef4570dbf4763a582e
